<?

return [
    'issetItems' => true,
    'items' => [
        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '1',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'с Транексамовой кислотой, витамином С...для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 3,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => true,
            'labels' => [
                [
                    'text' => 'Новинка'
                ],
                [
                    'text' => 'Хранить в холодильнике'
                ],
            ],
        ],
        [
            'strMainId' => 'bx002',
            'id' => '2',
            'detailPageUrl' => '#',
            'filter' => '1',
            'image' => [
                'src' => '/local/assets/images/catalog/image2.png',
                'mobileSrc' => '/local/assets/images/catalog/image2-mobile.png',
                'alt' => '1',
            ],
            'title' => 'Набор из трех масок',
            'text' => '«Увлажняющая», «Жемчужная лифтинг маска», «Очищающая»',
            'volume' => '100&nbsp;мл, 100мл, 100мл',
            'canBuy' => true,
            'maxQuantity' => 4,
            'price' => [
                'value' => 2646,
                'valueFormatted' => '2 646',
                'oldValue' => 4070,
                'oldValueFormatted' => '4 070',
                'discount' => '-35%',
                'currency' => '₽',
            ],
            'issetLabels' => true,
            'labels' => [
                [
                    'text' => 'Новинка'
                ],
            ],
        ],
        [
            'strMainId' => 'bx003',
            'id' => '3',
            'detailPageUrl' => '#',
            'filter' => '1',
            'image' => [
                'src' => '/local/assets/images/catalog/image3.png',
                'mobileSrc' => '/local/assets/images/catalog/image3-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Аромабокс',
            'text' => '«Семейная аптечка и иммунитет» (Эвкалипт, Чайное дерево, Мята, Лимон...',
            'volume' => '50 мл',
            'canBuy' => true,
            'maxQuantity' => 8,
            'price' => [
                'value' => 2952,
                'valueFormatted' => '2 952',
                'oldValue' => 3690,
                'oldValueFormatted' => '3 690',
                'discount' => '-20%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],

        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '2',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '1',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],
        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '1',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],
        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '1',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],
        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '1',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],
        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '1',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],
        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '2',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '1',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],
        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '1',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],
        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '1',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],
        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '1',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],
        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '1',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],


        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '3',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '1',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],

        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '4',
            'image' => [
                'src' => '/local/assets/images/catalog/image2.png',
                'mobileSrc' => '/local/assets/images/catalog/image2-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],

        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '5',
            'image' => [
                'src' => '/local/assets/images/catalog/image3.png',
                'mobileSrc' => '/local/assets/images/catalog/image3-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],

        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '6',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],

        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '7',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],

        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '8',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],

        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '9',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '2',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],

        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '10',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '1',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],

        [
            'strMainId' => 'bx001',
            'id' => '1',
            'detailPageUrl' => '#',
            'filter' => '11',
            'image' => [
                'src' => '/local/assets/images/catalog/image1.png',
                'mobileSrc' => '/local/assets/images/catalog/image1-mobile.png',
                'alt' => '1',
            ],
            'title' => 'Жемчужная лифтинг маска',
            'text' => 'для ровного тона кожи «Белоснежка» с Транексамовой кислотой, витамином С...',
            'volume' => '100&nbsp;мл',
            'canBuy' => true,
            'maxQuantity' => 10,
            'price' => [
                'value' => 1390,
                'valueFormatted' => '1 390',
                'oldValue' => 1590,
                'oldValueFormatted' => '1590',
                'discount' => '-15%',
                'currency' => '₽',
            ],
            'issetLabels' => false,
        ],
    ]
];